
groups: 

- name: Rack Nodes Down Alerts
  rules: 
  - alert: Rack Node Down
    expr: up { component_type=~"head|worker" } == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Rack Node Exporter target missing (instance {{ $labels.instance }})" 
      description: "A rack Node Exporter target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - alert: Rack node job missing
    expr: absent( up{ job="node", component_type=~"head|worker" } ) == 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Rack Node Exporter job is missing (instance {{ $labels.instance }})"
      description: "A rack Node Exporter job has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

