---
##############################################################
#                   Central Metrics                           #
##############################################################
# This section contains the tasks needed for installing the 
#   central metrics site.

- name: Install Fabric Central setup 
  block:
  - name: Install python sdk to manage docker
    become: yes
    import_tasks: install_docker_python_sdk_tasks.yml
    when: 
      - add_python_docker_sdk is defined
      - add_python_docker_sdk

  
  - name: Install Fabric Central Metrics
    import_tasks: fabric_central_install_tasks.yml

  # when: 
  #   - install_type is defined
  #   - install_type == 'central'


# - name: Change State of Fabric Central Docker Containers 
#   block:
  
#   - name: Change Container
#     import_tasks: container_tasks/change_docker_container_states_tasks.yml
#     #vars: 
#     # new_docker_state: absent - removes it | stopped - stops it | started - starts existing container
#     # containers_to_act_on
  
#   when: 
#     - install_type is defined
#     - install_type == 'central_shutdown'


# - name: Update Prometheus Alert Rules 
#   block: 
#   - name: Update prom config.
#     become: yes 
#     import_tasks: Prometheus/add_prometheus_config_templates.yml 

#   - name: Update Alertmanager.
#     become: yes 
#     import_tasks: Alertmanager/config_alertmanager_tasks.yml

#   - name: Stop Alertmanager. 
#     become: yes 
#     import_tasks: Alertmanager/alertmanager_container_tasks.yml
#     vars:
#       alertmanager_state: absent
#   - name: Restart Alertmanager. 
#     become: yes 
#     import_tasks: Alertmanager/alertmanager_container_tasks.yml
#   when:
#     - update_alerts is defined  
#     - update_alerts



