####################### FILEBEAT ##########################
# ansible-playbook site.yml --tags "filebeat" -v
###########################################################
# Check if Filebeat package is already downloaded
- name: Check if Filebeat package exists
  tags: filebeat 
  stat: 
    path: /tmp/filebeat-{{ filebeat_version }}-x86_64.rpm
  register: r_filebeat_package_exist 

# Download Filebeat
- name: Download Filebeat 
  tags: filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    r_filebeat_package_exist.stat.exists == false

# Install rsyslog using yum
- name: Install rsyslog
  tags: filebeat
  ansible.builtin.package:
    name: rsyslog
    state: present

# Install Filebeat using yum
- name: Install Filebeat
  tags: filebeat
  yum:
    name: /tmp/filebeat-{{ filebeat_version }}-x86_64.rpm
    state: present

# Copy the filebeat.yml 
- name: Copy Filebeat template file
  tags: filebeat
  template:
    src: "{{ filebeat_template_file }}"
    dest: /etc/filebeat/filebeat.yml

# Setup Filebeat
- name: Setup Filebeat
  tags: filebeat
  command: filebeat setup -e

# Start Filebeat
- name: Start Filebeat
  tags: filebeat
  service:
    name: filebeat
    state: restarted
    enabled: yes

####################### METRICBEAT ##########################
# ansible-playbook site.yml --tags "metricbeat" -v
#############################################################
# Check if Metricbeat package is already downloaded
- name: Check if Metricbeat package exists
  tags: metricbeat 
  stat: 
    path: /tmp/metricbeat-{{ metricbeat_version }}-x86_64.rpm
  register: r_metricbeat_package_exist 

# Download Metricbeat
- name: Download Metricbeat 
  tags: metricbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    r_metricbeat_package_exist.stat.exists == false

# Install Metricbeat using yum
- name: Install Metricbeat
  tags: metricbeat
  yum:
    name: /tmp/metricbeat-{{ metricbeat_version }}-x86_64.rpm
    state: present

# Copy the metricbeat.yml 
- name: Copy Metricbeat template file
  tags: metricbeat
  template:
    src: "{{ metricbeat_template_file }}"
    dest: /etc/metricbeat/metricbeat.yml

# Setup Metricbeat
- name: Setup Metricbeat
  tags: metricbeat
  command: metricbeat setup -e

# Start Metricbeat
- name: Start Metricbeat
  tags: metricbeat
  service:
    name: metricbeat
    state: restarted
    enabled: yes

####################### PACKETBEAT ##########################
# ansible-playbook site.yml --tags "packetbeat" -v
#############################################################
# Check if Packetbeat package is already downloaded
- name: Check if Packetbeat package exists
  tags: packetbeat 
  stat: 
    path: /tmp/packetbeat-{{ packetbeat_version }}-x86_64.rpm
  register: r_packetbeat_package_exist 

# Download Packetbeat
- name: Download Packetbeat 
  tags: packetbeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-{{ packetbeat_version }}-x86_64.rpm
    dest: /tmp/
  when:
    r_packetbeat_package_exist.stat.exists == false

# Install Packetbeat using yum
- name: Install Packetbeat
  tags: packetbeat
  yum:
    name: /tmp/packetbeat-{{ packetbeat_version }}-x86_64.rpm
    state: present

# Copy the packetbeat.yml 
- name: Copy Packetbeat template file
  tags: packetbeat
  template:
    src: "{{ packetbeat_template_file }}"
    dest: /etc/packetbeat/packetbeat.yml

# Setup Packetbeat
- name: Setup Packetbeat
  tags: packetbeat
  command: packetbeat setup -e

# Start Packetbeat
- name: Start Packetbeat
  tags: packetbeat
  service:
    name: packetbeat
    state: restarted
    enabled: yes
