--- 

####################
#       CEPH       #
####################
# Universal Rack User
ceph_bucket: <bucket>
ceph_endpoint: <ceph server>
ceph_access_key: <ceph acess>
ceph_secret_key: <ceph secret>