# Install packages (ansible on Measurement node)
- name: Installing packages in base/tasks/main.yml
  become: true
  tags: packages
  ansible.builtin.package:
    name:
      - ansible
      - git
      - rsyslog
    state: present
    #update_cache: yes
    # seems to cause issue with apt

