---
# Add a file or template to the redfish config directory
# Note that the template files are passed in without the .j2 suffix
- name: Add Redfish Config
  template:
    src: "{{ redfish_templates_dir }}/{{ item }}.j2"
    dest: "{{ base_install_dir }}/redfish/config/{{ item }}"
    owner: "{{ prom_user_name }}"
    group: "{{ prom_group_name }}"
  with_items: "{{ redfish_config_template_files }}"
  become: yes