---
# Create the base directories needed by redfish
- name: Create Redfish Exporter Directories
  block:
      
    - name: "Create Redfish directories"
      file:
        path: "{{ base_install_dir }}/redfish/{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ prom_user_name }}"
        group: "{{ prom_group_name }}"
      with_items:
        - [ "config" ]

  become: yes