---
# file: node_ping_alert_rules.yml
# location: all racks, central

groups: 

- name: Infrastructure Alerts
  rules:

  - alert: HeadNodePingFailed
    expr: probe_success {job="ping", component_type="head", reason="infrastructure_check"} == 0
    for: 5m
    labels: 
      severity: error 
      fabric_system: headnode
      fabric_response: system
    annotations: 
      summary: "Ping check, central metrics to headnode {{ $labels.subdomain }} on operations network ip {{ $labels.subdomain }} failed."
      description: "Ping check to see if headnode is up."

  - alert: WorkerNodePingFailed
    expr: probe_success {job="ping", component_type="worker", reason="infrastructure_check"} == 0
    for: 5m
    labels: 
      severity: error 
      fabric_system: headnode
      fabric_response: system
    annotations: 
      summary: "Ping check, central metrics to worker node {{ $labels.subdomain }} on operations network ip {{ $labels.subdomain }} failed."
      description: "Ping check to see if worker node is up."
