---

groups: 

- name: Certificate Alerts
  rules:

  - alert: SSLCertExpired
    expr: (probe_ssl_earliest_cert_expiry - time()) < 0
    for: 15m
    labels:
      severity: critical
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate has expired for {{ $labels.instance }}"   
      description:  "SSL Certificate has expired for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 

  - alert: SSLCertExpiringLessThan7Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 7)
    for: 15m
    labels:
      severity: critical
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 7 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 7 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
            
  - alert: SSLCertExpiringLessThan30Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 30)
    for: 15m
    labels:
      severity: warning
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 30 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 30 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
       
  - alert: SSLCertExpiringLessThan60Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 60)
    for: 15m
    labels:
      severity: info
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 60 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 60 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
      
#    - alert: SSLCertExpiring11m2d
#      expr: (probe_ssl_earliest_cert_expiry - time()) < 28673600
#      for: 15m
#      labels:
#        severity: test

