---

groups: 

- name: Blackbox Alerts
  #interval: 1m
  rules:

  - alert: VPN Ping Failed
    expr: probe_success {job="ping", reason="vpn"} == 0
    for: 1m
    labels:
      severity: warning
      fabric_system: vpn
    annotations:
      summary:  "VPN ping to {{ $labels.instance }} failed for 1 minute."   
      description:  "{{ $labels.instance }} did not respond to ping for 1 minute." 

  - alert: VPN Ping Failed
    expr: probe_success {job="ping", reason="vpn"} == 0
    for: 15m
    labels:
      severity: critical
      fabric_system: vpn 
    annotations:
      summary:  "VPN ping to {{ $labels.instance }} has failed for 15 minutes."   
      description:  "{{ $labels.instance }} has not responded to ping for more than 15 minutes." 

  - alert: HeadNodePingFailed
    expr: probe_success {job="ping", reason="infrastructure_check"} == 0
    for: 5m
    labels: 
      severity: error 
      fabric_system: headnode
    annotations: 
      summary: "Ping check, central metrics to headnode {{ $labels.subdomain }} on operations network ip {{ $labels.subdomain }} failed."
      description: "Ping check to see if headnode is up."

  - alert: Fabric Web Site Down
    expr: probe_success {job="blackbox-http", check_type="web-site"} == 0
    for: 5m
    labels: 
      severity: critical
      fabric_system: web_site
    annotations:
      summary:  "Web server {{ $labels.instance }} is down."   
      description:  "{{ $labels.instance }} has been down or not responding for more than 5 minutes." 


- name: Rack Nodes Down Alerts
  rules: 
  - alert: Rack Node Down
    expr: up { component_type=~"head|worker" } == 0
    for: 5m
    labels:
      severity: warning
      fabric_system: node_exporter
    annotations:
      summary:  "Rack Node Exporter target missing (instance {{ $labels.instance }})"   
      description:  "A rack Node Exporter target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}" 


  - alert: Rack node job missing
    expr: absent( up{ job="node", component_type=~"head|worker" } ) == 1
    for: 5m
    labels:
      severity: warning
      fabric_system: node_exporter
    annotations:
      summary:  "Rack Node Exporter job is missing (instance {{ $labels.instance }})"   
      description:  "A rack Node Exporter job has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}" 




- name: Certificate Alerts
  rules:

  - alert: SSLCertExpired
    expr: (probe_ssl_earliest_cert_expiry - time()) < 0
    for: 15m
    labels:
      severity: critical
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate has expired for {{ $labels.instance }}"   
      description:  "SSL Certificate has expired for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 

  - alert: SSLCertExpiringLessThan7Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 7)
    for: 15m
    labels:
      severity: critical
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 7 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 7 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
            
  - alert: SSLCertExpiringLessThan30Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 30)
    for: 15m
    labels:
      severity: warning
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 30 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 30 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
       
  - alert: SSLCertExpiringLessThan60Days
    expr: (probe_ssl_earliest_cert_expiry - time()) < (86400 * 60)
    for: 15m
    labels:
      severity: info
      fabric_system: SSL Certificate
    annotations:
      summary:  "SSL Certificate will expire in less than 60 days for {{ $labels.instance }}"   
      description:  "SSL Certificate will expire in less than 60 days for {{ $labels.instance }}.\n  Seconds = {{ $value }}\n  LABELS = {{ $labels }}" 
      
#    - alert: SSLCertExpiring11m2d
#      expr: (probe_ssl_earliest_cert_expiry - time()) < 28673600
#      for: 15m
#      labels:
#        severity: test


- name: PTP Alerts
  rules: 
  
  - alert: RackNodeNotTimeSynced
    expr: node_timex_sync_status { component_type=~"head|worker" } == 0 
    for: 15m
    labels:
      severity: error
      fabric_system: time
    annotations:
      summary:  "Time is not synced on node {{ $labels.instance }}"   
      description:  "node_timex_sync_status is 0 on {{ $labels.instance }}." 
      

  - alert: RackNodeTimexMaxErrorTooHigh
    expr: node_timex_maxerror_seconds{job="node", component_type=~"head|worker"} > 0.001
    for: 15m
    labels:
      severity: error
      fabric_system: time
    annotations:
      summary:  "Timex max error exceeded on node {{ $labels.instance }}"   
      description:  "node_timex_maxerror_seconds is > 0.001 on {{ $labels.instance }}. Indicates node is not time synced." 

  - alert: RackGPSTimeUnknown
    expr: tmiGPSTimeKnown  == 0
    for: 15m
    labels:
      severity: error
      fabric_system: time
    annotations:
      summary:  "GPS time is not known node {{ $labels.instance }}"   
      description:  "tmiGPSTimeKnown is 0 on {{ $labels.instance }}." 
      

  - alert: 2DGPSFix
    expr: tmiGPSFix == 1
    for: 15m
    labels:
      severity: info
      fabric_system: time
    annotations:
      summary:  "GPS time sync is only 2D on {{ $labels.instance }}"   
      description:  "tmiGPSFix is 2 on {{ $labels.instance }}." 
      

  - alert: NoGPSFix
    expr: tmiGPSFix == 0
    for: 15m
    labels: 
      severity: warning
      fabric_system: time
    annotations:
      summary:  "GPS time is not fixed on node {{ $labels.instance }}"   
      description:  "tmiGPSFix is 0 on {{ $labels.instance }}." 
      
